AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: The SAMQUest SAM template
Resources:
  ProcessTwitterFeed:
    Type: AWS::Serverless::Function
    Properties:
      Handler: process_twitter_feed_handler.lambda_handler
      Runtime: python3.6
      CodeUri: ./
      Timeout: 50
      MemorySize: 512
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
      Environment:
        Variables:
          CONSUMER_KEY: 'test'
          CONSUMER_SECRET: 'test'
          ACCESS_TOKEN_KEY: 'test'
          ACCESS_TOKEN_SECRET: 'test'
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
